- hosts: localhost
  connection: local
  gather_facts: False
  
  vars:
      ec2_region: eu-central-1
      machines: [ 'JenkinsServer', 'BuildNode', 'TargetNode']
  tasks:

    - name: Provision a Set of 3 instances
      ec2:
        key_name: SshKey
        group: "LAN-Security Group"
        instance_type: t2.micro
        region: "{{ ec2_region }}"
        image: ami-194cdc76
        wait: true
        exact_count: 1
        instance_tags: 
           Name: "{{ item }}"
           VPCName: "LAN"
        count_tag:
           Name: "{{ item }}"
        vpc_subnet_id: subnet-3a189077
        assign_public_ip: yes
      register: ec2
      with_items: "{{ machines }}"

    #- debug: msg="DEBUG="{{ item.tagged_instances.0.tags.Name}}""
    #  with_items: "{{ ec2.results }}"
      


    - name: Add Public IPs to host group
      add_host: 
        hostname: "{{ item.tagged_instances.0.tags.Name }}" 
        ansible_host: "{{ item.tagged_instances.0.private_ip }}"
        ansible_user: ec2-user
        groupname: FinalProjectServers
      with_items: "{{ ec2.results }}"



- name: Configure CI server
  hosts: JenkinsServer
  become: True
  gather_facts: true
  vars:
      ansible_ssh_private_key_file: ~/.ssh/SshKey.pem
      userName: jenkins
  roles:
    - geerlingguy.jenkins
    - ntp

  tasks:
    - name: Create .ssh folder
      file:
        path: "~{{ userName }}/.ssh"
        state: directory
        owner: "{{ userName }}"
        group: "{{ userName }}"
        mode: 0700

    - name: Upload pem file
      copy:
       src: ~/.ssh/SshKey.pem
       dest: "~{{ userName }}/.ssh/SshKey.pem"
       owner: "{{ userName }}"
       group: "{{ userName }}"
       mode: 0700

- name: Configure Build Node
  hosts: BuildNode
  become: True
  gather_facts: true
  vars:
      ansible_ssh_private_key_file: ~/.ssh/SshKey.pem
      userName: jenkins
  roles:
    - geerlingguy.java
    - ntp
    - git
    - packages
    - geerlingguy.docker
    - role: jenkins-agent
      userName: jenkins





- name: Configure Target Node
  hosts: TargetNode
  become: True
  gather_facts: true
  vars:
      ansible_ssh_private_key_file: ~/.ssh/SshKey.pem
      userName: jenkins
  roles:
    - ntp
    - packages
    - geerlingguy.docker
    - python
    - role: jenkins-agent
      userName: jenkins

